-- Creating Teams table
CREATE TABLE Teams (
    TEAM_ID INT PRIMARY KEY,
    MIN_YEAR INT,
    ABBREVIATION VARCHAR(10),
    NICKNAME VARCHAR(50),
    YEARFOUNDED INT,
    CITY VARCHAR(50),
    ARENA VARCHAR(100),
    ARENACAPACITY INT,
    OWNER VARCHAR(100),
    GENERALMANAGER VARCHAR(100),
    HEADCOACH VARCHAR(100),
    DLEAGUEAFFILIATION VARCHAR(100)
);
-- Creating Games table
CREATE TABLE Games (
    GAME_DATE_EST DATE,
    GAME_ID INT PRIMARY KEY,
    GAME_STATUS_TEXT VARCHAR(50),
    HOME_TEAM_ID INT,
    VISITOR_TEAM_ID INT,
    SEASON INT,
    PTS_home INT,
    FG_PCT_home DECIMAL(5,2),
    FT_PCT_home DECIMAL(5,2),
    FG3_PCT_home DECIMAL(5,2),
    AST_home INT,
    REB_home INT,
    PTS_away INT,
    FG_PCT_away DECIMAL(5,2),
    FT_PCT_away DECIMAL(5,2),
    FG3_PCT_away DECIMAL(5,2),
    AST_away INT,
    REB_away INT,
    HOME_TEAM_WINS BOOLEAN,
    FOREIGN KEY (HOME_TEAM_ID) REFERENCES Teams(TEAM_ID),
    FOREIGN KEY (VISITOR_TEAM_ID) REFERENCES Teams(TEAM_ID)
);
-- Creating Players table
CREATE TABLE Players (
    PLAYER_NAME VARCHAR(100),
    TEAM_ID INT,
    PLAYER_ID INT,
    SEASON INT,
	UNIQUE_ID VARCHAR(100) PRIMARY KEY,
    FOREIGN KEY (TEAM_ID) REFERENCES Teams(TEAM_ID)
);
-- Creating Player_Details table
CREATE TABLE PlayerDetails (
    PLAYER_ID INT PRIMARY KEY,
    PLAYER_NAME VARCHAR(100)
);
-- Creating Game_Details table
CREATE TABLE GameDetails (
    GAME_ID INT,
    TEAM_ID INT,
    TEAM_ABBREVIATION VARCHAR(10),
    TEAM_CITY VARCHAR(50),
    PLAYER_ID INT,
    PLAYER_NAME VARCHAR(100),
    FGM DECIMAL(5,2),
    FGA DECIMAL(5,2),
    FG3M DECIMAL(5,2),
    FG3A DECIMAL(5,2),
    FTM DECIMAL(5,2),
    FTA DECIMAL(5,2),
    AST DECIMAL(5,2),
    PF DECIMAL(5,2),
    PTS DECIMAL(5,2),
    SEASON INT,
	UNIQUE_ID VARCHAR(100),
    FOREIGN KEY (GAME_ID) REFERENCES Games(GAME_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES Teams(TEAM_ID),
	FOREIGN KEY (PLAYER_ID) REFERENCES PlayerDetails(PLAYER_ID)
);
-- Creating Ranking table
CREATE TABLE Ranking (
    TEAM_ID INT,
    SEASON_ID INT,
    STANDINGSDATE DATE,
    CONFERENCE VARCHAR(20),
    TEAM VARCHAR(100),
    G INT,
    W INT,
    L INT,
    W_PCT DECIMAL(5,2),
    --PRIMARY KEY (TEAM_ID, SEASON_ID, STANDINGSDATE),
    FOREIGN KEY (TEAM_ID) REFERENCES Teams(TEAM_ID)
);


